export default {
  Chargingconfirmation:'Charging confirmation',
  Chargingfailed:'Charging failed',
  Blockconfirmation:"Under confirmation",
  Blockconfirmationfailed:"Confirmation failed",
  showMore: 'Pull up to show more',
  loading: 'Loading...',
  noDatale: 'No more data',
  noWeb: 'No network',
  chainsName: 'Chain name',
  noO: 'The withdrawal quantity cannot be 0',
  adrInvalid: 'Invalid address',
  feeNoEnough: 'Insufficient handling fee',
  passNum: 'Exceed the number of coins that can be withdrawn',
  noRecord: 'No records',
  noAssets: 'No assets',
  noData: 'No data available',
  collectionAddress: 'Collection address',
  currency: 'Currency',
  ConfirmWithdrawalInformation: 'Confirm withdrawal information',
  nextStep: 'Next step',
  CopySucceeded: 'Copy succeeded',
  wallingAgreement: 'Warrin Protocol',
  set: 'Set up',
  nodeStructure: 'Node structure',
  walletManagement: 'Node management',
  editWallet: 'Edit Node',
  energyFlow: 'Energy flow',
  inviteFriends: 'Invite friends',
  whiteParper: 'White paper',
  myTeam: 'My team',
  assets: 'Assets',
  recording: 'Recording',
  recharge: 'Recharge',
  rechargeDetail: 'Recharge Details',
  withdrawal: 'Withdrawal',
  withdrawalDetail: 'Withdrawal Details',
  exchange: 'Exchange',
  wexchange: 'Exchange',
  wwexchange: 'WRT exchange',
  quantityAvailable: 'Quantity Available',
  currentPrice: 'Current price',
  communication: 'WoChat',
  currentProgress: 'Current progress',
  purchaseNode: 'Purchase node',
  price: 'Price',
  node: 'Node',
  chooseWallet: 'Choose a Node',
  repeatWallet: 'Node repeat',
  manageWallet: 'Manage Node',
  walletAddress: 'Node address',
  confirmPurchase: 'Confirm purchase',
  importWallet: 'Import Node',
  createWallet: 'Create a Node',
  createWalletSuccess: 'Create Node Success',
  changeWalletSuccess: 'Change Node Success',
  walletName: 'Node name',
  changeWalletName: 'Modify Node name',
  setSecurepwd: 'Set a secure password',
  passwordInputError: 'Support 4-16 bit of characters, Chinese, upper & lower case letters, numbers',
  nameInputError: 'Password shall be a combination of English and numbers, up to 16 characters in total',
  repeatInputError: 'The two passwords entered are different',
  enterSecurityCodeAgain: 'Enter the security code again',
  created: 'Created',
  change: 'Change',
  options: 'Options',
  createError: 'Creation failed, please try again',
  verifyMnemonic: 'Verification mnemonic',
  backupMnemonic: 'Backup mnemonic',
  mnemonicTips: 'The mnemonic phrase is the unencrypted plaintext private key of your account, which is the certificate of ownership of the account, and its utility is roughly equivalent to: ID card.',
  mnemonicTips2: 'Be sure to copy the mnemonic words shown below on physical media',
  mnemonicTips3: 'And keep it properly, don’t take screenshots',
  jumpOver: 'Jump over',
  inspectionPasswd: 'Approved',
  introductionMnemonics: 'Introduction to mnemonics',
  backupnow: 'Back up now',
  exportMnemonic: 'Export mnemonic',
  precautions: 'Precautions',
  empty: 'Empty',
  confirmOnce: 'Confirm at once',
  mnemonicDictation: 'Write your Node mnemonic phrase silently',
  mnemonicImport: 'Mnemonic import',
  inputMnemonic: 'Please enter the mnemonic',
  backupSuccess: 'Successful backup',
  pleaseInputMnemonic: 'Please fill in your private key',
  importErrorNotSupportAddress: 'Import failed, address is not supported',
  privateKeyImport: 'Private key import',
  enterSecurePassword: 'Enter a secure password',
  setSecurePassword: 'Set a secure password',
  mnemonicVerificationError: 'Mnemonic Verification Error',
  clearlyWords: 'Clearly fill in your mnemonic words, separated by spaces between English words',
  enterSpaces: 'Enter mnemonic words, separated by spaces',
  startImport: 'Start import',
  importSuccess: 'Imported successfully',
  resetSuccess: 'Reset successfully',
  changePassword: 'change Password',
  languageSwitch: 'Language switch',
  versionUpdate: 'New version update',
  latestVersion: 'Latest Version',
  version: 'Version',
  home: 'Home',
  savePicture: 'Save Picture',
  time: 'Time',
  orderType: 'Order Type',
  recharges: 'Recharge',
  rechargeAddress: 'Recharge Address',
  remarks: 'Remarks',
  detail: 'Details',
  fundingDetails: 'Funding Details',
  directPushReward: 'Direct push reward',
  nodeRevenue: 'Node revenue',
  multiDimensional: 'Multi-dimensional computing power reward',
  handlingFee: 'Handling fee',
  depositWithdrawal: 'Filling record',
  enterInvitationCode: 'Enter the invitation code',
  leaseEnterActivationCode: 'Please enter the activation code',
  definite: 'Definite',
  cancel: 'Cancel',
  identityActivationCodeError: 'Identity activation code error',
  activatedSuccessfully: 'Activated successfully',
  successfulRedemption: 'Successful redemption',
  hash: 'Hash',
  progressRate: 'Progress rate',
  quantity: 'Quantity',
  confirmChanges: 'Confirm the changes',
  originalpwd: 'Old password',
  enterOriginalpwd: 'Enter the original password',
  newpwd: 'New password',
  enternewpwd: 'Enter a new password',
  confirmNewPwd: 'Confirm the new password',
  notActive: 'Inactivated',
  enterpwdAgain: 'Enter the new password again',
  importMnemonicword: 'Import mnemonic words',
  importMnemonicWordTips: 'Please input correct mnemonic words, which are composed of 12 words',
  forgetpwdNeedNeset: 'If you forget your password, you need to reset it',
  enterSecurepassword: 'Please enter a secure password',
  securityPwdErr: 'Security password error',
  successfulPurchase: 'Successful purchase',
  currentWallet: 'Current Node',
  deleteWallet: 'Delete Node',
  chainName: 'Chain name',
  numberWithdrawals: 'Withdrawal quantity',
  extractable: 'Extractable',
  enterwithdrawalQuantity: 'Please enter the withdrawal quantity',
  address: 'Address',
  enterAddress: 'Please enter the address',
  actuallyArrived: 'Actually arrived',
  depositAddress: 'Deposit address',
  copy: 'Copy',
  note: 'Note',
  minimumWithdrawalAmount: 'The minimum withdrawal amount is ',
  manuallyReviewWithdrawal: 'We will manually review the withdrawal, please be patient.',
  pleaseEnsureSecurityDevice: 'Please ensure the security of the device and browser to prevent information from being tampered with or leaked.',
  successfulDeposit: 'Successful deposit',
  success: 'Success',
  numberDeposits: 'Number of deposits',
  blockConfirmation: 'Block confirmation',
  successfulWithdrawal: 'Successful withdrawal',
  totalAssets: 'Total assets',
  enterWalletName: 'Please enter the Node name',
  oldName: 'Original name',
  yourMnemonic: 'Your mnemonic',
  toVerify: 'To Verify',
  enterSecurityPwdAgain: 'Please enter the security password again',
  SecurityPwd: 'Security password',
  totalStormPool: 'Total storm pool',
  countdown: 'Countdown',
  amountCoinsDistributed: 'Amount of coins distributed',
  coinPrice: 'Coin price',
  news: 'News',
  seeDetail: 'See details',
  setCenter: 'Set the center',
  currentVersion: 'Current version',
  chooseLanguage: 'Choose a language',
  withdrawalAddress: 'Withdrawal Address',
  nodeNum: 'Node Number',
  pliesNum: 'Layer Number',
  plies: 'Layer',
  nodeLog: 'Node record',
  mine: 'Mine',
  refining: 'Refining',
  viewAsset: 'View assets',
  directPushNum: 'Direct push number',
  directPushNode: 'Direct push Node',
  mutiPowerIncome: 'Multi Power Income',
  getSum: 'Accumulated',
  myActiveId: 'My ID activation code',
  getSharePage: 'Get posters',
  purchaseQuantity: 'Purchase quantity',
  numberNurchase: 'The layer number of purchase',
  purchasePrice: 'The purchase price',
  confirmActivation: 'Confirm activation',
  stormPool: 'What is Storm Pool',
  stormPoolTips: 'For each new node, 1 USDT will enter the storm pool. If no new node is added within 72 hours, the storm pool will be triggered. The last node will receive 10% of the storm pool balance. All nodes on the last layer will equally share 30% of the storm pool balance. The remaining 60% is allocated from one layer to the two layers to all nodes. After the allocation is complete, add nodes and the storm pool will restart!',
  activateWallet: 'Activate Node',
  deleteSuccess: 'successfully deleted',
  ibought: 'I bought',
  oneNode: 'One node',
  securityCode: 'Security Code',
  canUseAmount: 'Can Use',
  duihuanList: 'History',
  duihuanNum: 'Exchange Amount',
  wduihuanNum: 'Exchange Amount',
  pleaseInputNum: 'Please Input Amount',
  PleaseClick: 'Please select',
  Pleaseinput: 'Please input',
  WithdrawoK: 'Withdraw money successfully',
  usdtText: 'The usdt withdrawal fee collected will be converted into ETH&TRX in dextraker through smart contract as the withdrawal fee of users. Usdt service charge will be adjusted according to ETH&TRX  network congestion. Please know.',
  reload: 'Reload',
  viewWhiteParper: 'View WhiteParper',
  updata: 'UpData',
  updataTo: 'UpData to',
  towernotopen: 'The tower is not open',
  wrongWalletName: 'Wrong Node name',
  insufficientBalanceRecharge: 'Insufficient balance, please go to recharge',
  switchSuccessfully: 'Switch successfully',
  smeltingRecord: 'Record',
  pleaseInputAmount: 'Please input amount',
  exchangeTip1: 'Amount can not be zero',
  exchangeTip2: 'The number of castings cannot be greater than the available number',
  wexchangeTip1: 'Amount can not be zero',
  wexchangeTip2: 'The number of castings cannot be greater than the available number',
  exchangeTip3: 'Exchange success',
  exchangeTip4: 'Exchange failure',
  wexchangeTip3: 'Exchange success',
  wexchangeTip4: 'Exchange failure',
  pickPoster: 'Pick Poster',
  shareTo: 'Share to',
  wx: 'Wechat',
  saveImg: 'Save Image',
  saveSuccess: 'Save Success',
  copySuccsee: 'Copy Success',
  copyFailure: 'Copy Failure',
  welcomeRegister: 'Welcome to register for Warlin',
  longPressToScan: 'Long press to identify the QR code',
  fileDownload: 'File Download, Loadings',
  noNetwork: 'No network',
  packInfo: 'Project Info',
  load: 'loading',
  uptoshowmore: 'Pull up to show more',
  nomoredata: 'No more data',
  deleteWalletSuccess: 'Delete Node Success',
  releaseUpdate: 'Release & update',
  downUpdate: 'Pull down to refresh',
  loadSuccess: 'Loading succeeded',
  loadError: 'Loading failed',
  myRecommendation: 'My recommendation',
  openingSoom: 'Open soon',

  invalidactivationcode: 'Invalid activation',
  nodeActivated: 'Node activated',
  activationFails: 'Activation fails',

  totalCirculation: 'Total circulation',
  totalDistributed: 'Total distributed',
  cumulativeTotalAmountDestruction: 'Cumulative total amount of destruction'
}
